config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root to: 'welcome#index'
  resources :products
  resources :order_items
  resource :card, only: :show
  post 'card_submit', to: 'cards#submit'

  devise_for :users
  ActiveAdmin.routes(self)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/only_admin_authorization.rb
class OnlyAdminAuthorization < ActiveAdmin::AuthorizationAdapter
  def authorized?(action, subject = nil)
    user.admin?
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  belongs_to :user
  before_save :set_subtotal
  accepts_nested_attributes_for :order_items, allow_destroy: true

  # unpublished - неоформленный заказ. в корзине пользователя (виден только юзеру в корзине)
  # claimed - сформированный заказ
  # in_progress - заказ в работе
  # done - завершенный заказ
  # rejected - отклоненный заказ
  enum status: [:unpublished, :claimed, :in_progress, :done, :rejected]

  def subtotal
    order_items.collect{ |order_item| order_item.valid? ? order_item.unit_price * order_item.quantity : 0 }.sum
  end

  def amount
    order_items.collect{ |order_item| order_item.valid? ? order_item.quantity : 0 }.sum
  end

  private

  def set_subtotal
    self.subtotal = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  before_save :set_unit_price
  before_save :set_total

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total
    unit_price * quantity
  end

  private

  def set_unit_price
    self[:unit_price] = unit_price
  end

  def set_total
    self[:total] = total
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_items
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: [:user, :admin]

  has_many :products
  has_many :orders

  def full_name
    [last_name, middle_name, first_name].compact.join(' ').chomp
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  include ApplicationHelper

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def access_denied(exception)
    redirect_to root_path, alert: exception.message
  end

  def user_not_authorized
    redirect_to new_user_session_path, alert: "Данное действие доступно только для авторизованных пользователей."
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def show
    @order = current_order
    @order_items = current_order.order_items
  end

  def submit
    order = current_order
    order.comment = card_params[:comment].presence
    order.status = :claimed
    if order.save
      flash[:notice] = 'Заказ был успешно сформирован!'
      session.delete(:order_id)

      OrderMailer.with(order: order).new_order_email.deliver_now
      OrderMailer.with(order: order).new_order_email_user.deliver_now
      redirect_to root_path
    else
      flash[:alert] = "Произошла ошибка. Попробуйте позднее."
      redirect_to card_path
    end
  end

  private

  def card_params
    params.require(:order).permit(:comment)
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def create
    @order = current_order
    @order_item = @order.order_items.new(order_params)
    @order.user = current_user
    @order.save
    session[:order_id] = @order.id
  end

  def update
    @order = current_order
    @order.user ||= current_user
    @order_item = @order.order_items.find(params[:id])
    @order_item.update(order_params)
    @order_items = current_order.order_items
  end

  def destroy
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
    @order_items = current_order.order_items
  end

  private

  def order_params
    params.require(:order_item).permit(:product_id, :quantity)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
    @order_item = current_order.order_items.new
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)
    @product.user = current_user

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Изделие было успешно создано." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Изделие было успешно обновлено." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Изделие было успешно удалено." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :weight, :expiration_days, :composition)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_order
    if !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cards/_card.html.erb
<%= link_to "Корзина (#{current_order.amount})", card_path, id: 'card', class: 'me-3 py-2 text-white text-decoration-none' %>

app/views/cards/_cards_item.html.erb
<div class="album py-5 bg-light">
    <div class="container">
      <h1>Корзина</h1>
      <hr>
      <br>
      <% if @order_items.present? %>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 mb-3">
          <% @order_items.each do |item| %>
            <div class="col">
              <div class="card shadow-sm">
                <div class="card-body">
                  <h4><%= link_to item.product.name, product_path(item.product), class: 'fw-bold text-reset text-decoration-none' %></h4>
                  <h5><%= item.product.price %> руб/шт.</h5>
                  <div class="d-flex justify-content-between align-items-center mt-3 mb-3 btn-group">
                    <%= form_for item, remote: true do |f| %>
                      <%= f.hidden_field :product_id, :value => item.product.id %>
                      <%= f.number_field :quantity, :value => item.quantity.to_i, class: 'form-control mb-3 mr-3' %>
                      <%= f.submit "Обновить", class: 'btn btn-sm btn-warning' %>
                      <%= link_to "Удалить товар", order_item_path(item), method: :delete, remote: true, class: 'btn btn-sm btn-outline-warning' %>
                    <% end %>
                  </div>
                  <h5>Цена: <%= item.total %> руб.</h5>
                </div>
              </div>
            </div>
          <% end %>
        </div>
        <hr>
        <h4 class="mb-3">Общая сумма заказа: <%= current_order.subtotal %> руб.</h4>
        <%= form_for :order, url: card_submit_path, method: :post do |f| %>
          Комментарий к заказу: <%= f.text_area :comment, class: 'form-control mt-3' %><br />
          <h5 class="mb-3">Минимальное кол-во изделий для заказа не менее 30 единиц</h5>
          <h5 class="mb-3">Доставка осуществляется на следующий день после поступления заказа. Прием заказов до 13.00.</h5>
          <h5 class="mb-3">Если заказ оформлен после 13.00, то доставка произойдет на второй день после дня заказа (послезавтра).</h5>
          <h5 class="mb-3">Заказ на количество изделий от 300 штук одного наименования требует дополнительного обсуждения с менеджером, зависит от загруженности производственных мощностей.</h5>
          <h5 class="mb-3">Всю информацию о доставке можно уточнить у менеджера.</h5>
          <%= f.submit 'Оформить заказ', data: { confirm: "Вы уверены что хотите создать заказ?" }, class: 'btn btn-lg btn-success'  %>
        <% end %>
        <br>
      <% else %>
        <h4 class="mb-3">Ваша корзина пока что пуста ¯\_(ツ)_/¯</h4>
        <%= link_to 'К изделиям', products_path, class: 'h5 text-decoration-none' %>
      <% end %>
    </div>
  </div>

app/views/cards/show.html.erb
<div id="card-item">
<%= render 'cards_item'%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KarpovaProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-light">
    <header class="mb-5">
      <nav class="navbar navbar-dark bg-dark">
        <div class="container">
          <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
            <%= render 'cards/card' %>
            <%= link_to 'Изделия', products_path, class: 'me-3 py-2 text-white text-decoration-none' %>
            <% if current_user && current_user.admin? %>
              <%= link_to 'Управление', admin_root_path, class: 'me-3 py-2 text-white text-decoration-none' %>
            <% end %>
            <% if user_signed_in? %>
              <%= link_to 'Выйти', destroy_user_session_path, method: :delete, class: 'py-2 text-warning text-decoration-none' %>
            <% else %>
              <%= link_to 'Войти', new_user_session_path, class: 'py-2 text-warning text-decoration-none' %>
            <% end %>
          </nav>
        </div>
      </nav>
      <div id="flash">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
      </div>
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/order_items/create.js.erb
$('#card').html("<%= escape_javascript(render('cards/card'))%>")

app/views/order_items/destroy.js.erb
$('#card').html("<%= escape_javascript(render('cards/card'))%>")
$('#card-item').html("<%= escape_javascript(render('cards/cards_item')) %>")

app/views/order_items/update.js.erb
$('#card').html("<%= escape_javascript(render('cards/card'))%>")
$('#card-item').html("<%= escape_javascript(render('cards/cards_item')) %>")

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <p>
      <%= form.label :name, 'Название' %>
      <%= form.text_field :name, class: 'form-control' %>
    </p>

    <p>
      <%= form.label :description, 'Описание' %>
      <%= form.text_area :description, rows: 5, class: 'form-control' %>
    </p>

    <p>
      <%= form.label :price, 'Цена' %>
      <%= form.number_field :price, in: 1.0..20.0, step: 0.5, class: 'form-control' %>
    </p>

    <p>
      <%= form.label :weight, 'Вес (кг)' %>
      <%= form.number_field :weight, step: :any, class: 'form-control' %>
    </p>

    <p>
      <%= form.label :expiration_days, 'Срок годности (дней)' %>
      <%= form.number_field :expiration_days, class: 'form-control' %>
    </p>

    <p>
      <%= form.label :composition, 'Состав' %>
      <%= form.text_area :composition, class: 'form-control' %>
    </p>

    <div class="d-flex justify-content-between align-items-center">
      <%= form.submit 'Сохранить изменения', class: "btn btn-outline-success" %>
      <%= link_to 'Назад', products_path, class: 'btn btn-sm btn-outline-secondary' %>
    </div>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <h1>Редактирование изделия</h1>
    <hr>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      <div class="col">
        <div class="card shadow-sm">
          <%= image_tag("bread#{params[:id]}") %>

          <div class="card-body">
            <%= render 'form', product: @product %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="album py-5 bg-light">
    <div class="container">
      <h1>Каталог изделий</h1>
      <hr>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <% @products.each_with_index do |product, i| %>
          <div class="col">
            <div class="card shadow-sm">
              <%= image_tag("bread#{i+1}") %>
              <div class="card-body">
                <%= link_to product.name, product_path(product), class: 'h4 fw-bold text-reset text-decoration-none' %>
                <div class="d-flex justify-content-between align-items-center mt-3">
                  <%= form_for @order_item, remote: true do |f|%>
                    <%= f.hidden_field :product_id, :value => product.id %>
                    <%= f.number_field :quantity, :value => 1, :min => 1, class: 'form-control mb-3 mr-3' %>
                    <div class="btn-group">
                      <% if current_user.admin? %>
                        <%= link_to 'Изменить', edit_product_path(product), class: 'btn btn-sm btn-outline-secondary' %>
                      <% end %>
                      <%= f.submit "Купить", class: 'btn btn-sm btn-warning' %>
                    </div>
                    <small class="text-muted">Цена: <%= product.price %> руб.</small>
                  <% end %>
                </div>

              </div>
            </div>
          </div>
        <% end %>
      </div>
      <br>
    </div>
  </div>

app/views/products/new.html.erb
<h1>Добавить изделие</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <h1>Просмотр изделия</h1>
    <hr>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      <div class="col">
        <div class="card shadow-sm">
          <%= image_tag("bread#{params[:id]}") %>
          <div class="card-body">
            <h4 class="card-text fw-bold"><%= @product.name %></h4>
            <hr>
            <p class="card-text"><%= @product.description %></p>
            <p class="card-text"><strong>Цена:</strong> <%= @product.price %> руб</p>
            <p class="card-text"><strong>Вес:</strong> <%= @product.weight %> кг</p>
            <p class="card-text"><strong>Срок годности:</strong> <%= @product.expiration_days %> дня(ей)</p>
            <p class="card-text"><strong>Состав:</strong> <%= @product.composition %></p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <button type="button" class="btn btn-sm btn-dark">В корзину</button>
                <% if current_user.admin? %>
                  <%= link_to 'Изменить', edit_product_path(@product), class: 'btn btn-sm btn-outline-secondary' %>
                <% end %>
                <%= link_to 'Назад', products_path, class: 'btn btn-sm btn-outline-secondary' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<main>
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h2 class="fw-light">Модуль для контроля и учета заказов</h2>
        <p class="lead text-muted">Здесь Вы можете заказать изделия, произведенные на хлебозаводе "N"</p>
        <p>
          <% unless current_user %>
            <%= link_to 'Авторизоваться', new_user_session_path, class: 'btn btn-primary my-2' %>
          <% end %>
          <%= link_to 'Смотреть изделия', products_path, class: 'btn btn-secondary my-2' %>
        </p>
      </div>
    </div>
  </section>
</main>